/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableIndexerSearchAPIModule.h"

IMPLEMENT_MODULE(ImmutableIndexerSearchAPIModule, ImmutableIndexerSearchAPI);
DEFINE_LOG_CATEGORY(LogImmutableIndexerSearchAPI);

void ImmutableIndexerSearchAPIModule::StartupModule()
{
}

void ImmutableIndexerSearchAPIModule::ShutdownModule()
{
}
