/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIStacksApiOperations.h"

#include "ImmutableIndexerSearchAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace ImmutableIndexerSearchAPI
{

FString OpenAPIStacksApi::BackfillRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("chain_name"), FStringFormatArg(ToUrlString(ChainName)) } };

	FString Path = FString::Format(TEXT("/v1/internal/chains/{chain_name}/backfill"), PathParams);

	return Path;
}

void OpenAPIStacksApi::BackfillRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = { TEXT("application/json") };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("POST"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
		// Body parameters
		FString JsonBody;
		JsonWriter Writer = TJsonWriterFactory<>::Create(&JsonBody);

		WriteJsonValue(Writer, OpenAPIBackfillRequest);
		Writer->Close();

		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json; charset=utf-8"));
		HttpRequest->SetContentAsString(JsonBody);
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
		UE_LOG(LogImmutableIndexerSearchAPI, Error, TEXT("Body parameter (OpenAPIBackfillRequest) was ignored, not supported in multipart form"));
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
		UE_LOG(LogImmutableIndexerSearchAPI, Error, TEXT("Body parameter (OpenAPIBackfillRequest) was ignored, not supported in urlencoded requests"));
	}
	else
	{
		UE_LOG(LogImmutableIndexerSearchAPI, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void OpenAPIStacksApi::BackfillResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 202:
		SetResponseString(TEXT("Accepted"));
		break;
	case 400:
		SetResponseString(TEXT("Bad Request (400)"));
		break;
	case 404:
		SetResponseString(TEXT("The specified resource was not found (404)"));
		break;
	case 500:
		SetResponseString(TEXT("Internal Server Error (500)"));
		break;
	}
}

bool OpenAPIStacksApi::BackfillResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return true;
}

FString OpenAPIStacksApi::SearchNFTsRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("chain_name"), FStringFormatArg(ToUrlString(ChainName)) } };

	FString Path = FString::Format(TEXT("/experimental/chains/{chain_name}/search/nfts"), PathParams);

	TArray<FString> QueryParams;
	if(AccountAddress.IsSet())
	{
		QueryParams.Add(FString(TEXT("account_address=")) + ToUrlString(AccountAddress.GetValue()));
	}
	if(StackId.IsSet())
	{
		QueryParams.Add(CollectionToUrlString_multi(StackId.GetValue(), TEXT("stack_id")));
	}
	if(OnlyIncludeOwnerListings.IsSet())
	{
		QueryParams.Add(FString(TEXT("only_include_owner_listings=")) + ToUrlString(OnlyIncludeOwnerListings.GetValue()));
	}
	if(PageSize.IsSet())
	{
		QueryParams.Add(FString(TEXT("page_size=")) + ToUrlString(PageSize.GetValue()));
	}
	if(PageCursor.IsSet())
	{
		QueryParams.Add(FString(TEXT("page_cursor=")) + ToUrlString(PageCursor.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void OpenAPIStacksApi::SearchNFTsRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

}

void OpenAPIStacksApi::SearchNFTsResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
		SetResponseString(TEXT("200 response"));
		break;
	case 400:
		SetResponseString(TEXT("Bad Request (400)"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorised Request (401)"));
		break;
	case 403:
		SetResponseString(TEXT("Forbidden Request (403)"));
		break;
	case 404:
		SetResponseString(TEXT("The specified resource was not found (404)"));
		break;
	case 429:
		SetResponseString(TEXT("Too Many Requests (429)"));
		break;
	case 500:
		SetResponseString(TEXT("Internal Server Error (500)"));
		break;
	}
}

bool OpenAPIStacksApi::SearchNFTsResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

inline FString ToString(const OpenAPIStacksApi::SearchStacksRequest::SortByEnum& Value)
{
	switch (Value)
	{
	case OpenAPIStacksApi::SearchStacksRequest::SortByEnum::CheapestFirst:
		return TEXT("cheapest_first");
	}

	UE_LOG(LogImmutableIndexerSearchAPI, Error, TEXT("Invalid OpenAPIStacksApi::SearchStacksRequest::SortByEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIStacksApi::SearchStacksRequest::EnumToString(const OpenAPIStacksApi::SearchStacksRequest::SortByEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIStacksApi::SearchStacksRequest::SortByEnum& Value)
{
	static TMap<FString, OpenAPIStacksApi::SearchStacksRequest::SortByEnum> StringToEnum = { 
		{ TEXT("cheapest_first"), OpenAPIStacksApi::SearchStacksRequest::SortByEnum::CheapestFirst }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIStacksApi::SearchStacksRequest::EnumFromString(const FString& EnumAsString, OpenAPIStacksApi::SearchStacksRequest::SortByEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIStacksApi::SearchStacksRequest::SortByEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIStacksApi::SearchStacksRequest::SortByEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

FString OpenAPIStacksApi::SearchStacksRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("chain_name"), FStringFormatArg(ToUrlString(ChainName)) } };

	FString Path = FString::Format(TEXT("/experimental/chains/{chain_name}/search/stacks"), PathParams);

	TArray<FString> QueryParams;
	QueryParams.Add(CollectionToUrlString_multi(ContractAddress, TEXT("contract_address")));
	if(AccountAddress.IsSet())
	{
		QueryParams.Add(FString(TEXT("account_address=")) + ToUrlString(AccountAddress.GetValue()));
	}
	if(OnlyIncludeOwnerListings.IsSet())
	{
		QueryParams.Add(FString(TEXT("only_include_owner_listings=")) + ToUrlString(OnlyIncludeOwnerListings.GetValue()));
	}
	if(OnlyIfHasActiveListings.IsSet())
	{
		QueryParams.Add(FString(TEXT("only_if_has_active_listings=")) + ToUrlString(OnlyIfHasActiveListings.GetValue()));
	}
	if(Trait.IsSet())
	{
		QueryParams.Add(FString(TEXT("trait=")) + ToUrlString(Trait.GetValue()));
	}
	if(Keyword.IsSet())
	{
		QueryParams.Add(FString(TEXT("keyword=")) + ToUrlString(Keyword.GetValue()));
	}
	if(SortBy.IsSet())
	{
		QueryParams.Add(FString(TEXT("sort_by=")) + ToUrlString(SortBy.GetValue()));
	}
	if(PageSize.IsSet())
	{
		QueryParams.Add(FString(TEXT("page_size=")) + ToUrlString(PageSize.GetValue()));
	}
	if(PageCursor.IsSet())
	{
		QueryParams.Add(FString(TEXT("page_cursor=")) + ToUrlString(PageCursor.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void OpenAPIStacksApi::SearchStacksRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

}

void OpenAPIStacksApi::SearchStacksResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
		SetResponseString(TEXT("200 response"));
		break;
	case 400:
		SetResponseString(TEXT("Bad Request (400)"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorised Request (401)"));
		break;
	case 403:
		SetResponseString(TEXT("Forbidden Request (403)"));
		break;
	case 404:
		SetResponseString(TEXT("The specified resource was not found (404)"));
		break;
	case 429:
		SetResponseString(TEXT("Too Many Requests (429)"));
		break;
	case 500:
		SetResponseString(TEXT("Internal Server Error (500)"));
		break;
	}
}

bool OpenAPIStacksApi::SearchStacksResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
