/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace ImmutableIndexerSearchAPI
{

/*
 * OpenAPIPage
 *
 * Pagination properties
 */
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIPage : public Model
{
public:
    virtual ~OpenAPIPage() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* First item as an encoded string */
	TOptional<FString> PreviousCursor;
	/* Last item as an encoded string */
	TOptional<FString> NextCursor;
};

}
