/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPINFTBundle.h"
#include "OpenAPIPage.h"

namespace ImmutableIndexerSearchAPI
{

/*
 * OpenAPISearchNFTsResult
 *
 * Search NFTs result
 */
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPISearchNFTsResult : public Model
{
public:
    virtual ~OpenAPISearchNFTsResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of nft bundles */
	TArray<OpenAPINFTBundle> Result;
	OpenAPIPage Page;
};

}
