/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIStacksApi.h"

#include "OpenAPIAPIError400.h"
#include "OpenAPIAPIError401.h"
#include "OpenAPIAPIError403.h"
#include "OpenAPIAPIError404.h"
#include "OpenAPIAPIError429.h"
#include "OpenAPIAPIError500.h"
#include "OpenAPIBackfillRequest.h"
#include "OpenAPISearchNFTsResult.h"
#include "OpenAPISearchStacksResult.h"

namespace ImmutableIndexerSearchAPI
{

/* Backfills or re-indexes a given entity
 *
 * Backfills or re-indexes a given entity
*/
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIStacksApi::BackfillRequest : public Request
{
public:
    virtual ~BackfillRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	OpenAPIBackfillRequest OpenAPIBackfillRequest;
};

class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIStacksApi::BackfillResponse : public Response
{
public:
    virtual ~BackfillResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    
};

/* Experimental: Search NFTs
 *
 * ![Experimental](https://img.shields.io/badge/status-experimental-yellow) Search NFTs
*/
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIStacksApi::SearchNFTsRequest : public Request
{
public:
    virtual ~SearchNFTsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* Account address to filter by */
	TOptional<FString> AccountAddress;
	/* Filters NFTs that belong to any of these stacks */
	TOptional<TArray<FGuid>> StackId;
	/* Whether the listings should include only the owner created listings */
	TOptional<bool> OnlyIncludeOwnerListings;
	/* Number of results to return per page */
	TOptional<int32> PageSize;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIStacksApi::SearchNFTsResponse : public Response
{
public:
    virtual ~SearchNFTsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPISearchNFTsResult Content;
};

/* Experimental: Search NFT stacks
 *
 * ![Experimental](https://img.shields.io/badge/status-experimental-yellow) Search NFT stacks
*/
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIStacksApi::SearchStacksRequest : public Request
{
public:
    virtual ~SearchStacksRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* List of contract addresses to filter by */
	TArray<FString> ContractAddress;
	/* Account address to filter by */
	TOptional<FString> AccountAddress;
	/* Whether to the listings should include only the owner created listings */
	TOptional<bool> OnlyIncludeOwnerListings;
	/* Filters results to include only stacks that have a current active listing. False and 'null' return all unfiltered stacks. */
	TOptional<bool> OnlyIfHasActiveListings;
	/* JSON encoded traits to filter by. e.g. encodeURIComponent(JSON.stringify({\"rarity\": {\"values\": [\"common\", \"rare\"], \"condition\": \"eq\"}})) */
	TOptional<FString> Trait;
	/* Keyword to search NFT name and description. Alphanumeric characters only. */
	TOptional<FString> Keyword;
	enum class SortByEnum
	{
		CheapestFirst,
  	};

	static FString EnumToString(const SortByEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortByEnum& EnumValue);
	/* Sort results in a specific order */
	TOptional<SortByEnum> SortBy;
	/* Number of results to return per page */
	TOptional<int32> PageSize;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIStacksApi::SearchStacksResponse : public Response
{
public:
    virtual ~SearchStacksResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPISearchStacksResult Content;
};

}
