/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIMarketPriceDetails.h"

namespace ImmutableIndexerSearchAPI
{

/*
 * OpenAPIListing
 *
 * Listing
 */
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIListing : public Model
{
public:
    virtual ~OpenAPIListing() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Global Order identifier */
	FString ListingId;
	OpenAPIMarketPriceDetails PriceDetails;
	/* Token ID */
	FString TokenId;
	/* ETH Address of listing creator */
	FString Creator;
	/* Amount of token included in the listing */
	FString Amount;
};

}
