/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIChain.h"
#include "OpenAPINFTMetadataAttribute.h"

namespace ImmutableIndexerSearchAPI
{

/*
 * OpenAPINFTWithStack
 *
 * Stack
 */
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPINFTWithStack : public Model
{
public:
    virtual ~OpenAPINFTWithStack() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Token id of NFT (uint256 as string) */
	FString TokenId;
	/* Stack ID */
	FGuid StackId;
	OpenAPIChain Chain;
	/* Contract address */
	FString ContractAddress;
	/* When the metadata was created */
	FDateTime CreatedAt;
	/* When the metadata was last updated */
	FDateTime UpdatedAt;
	/* The name of the NFT */
	TOptional<FString> Name;
	/* The description of the NFT */
	TOptional<FString> Description;
	/* The image url of the NFT */
	TOptional<FString> Image;
	/* The external website link of NFT */
	TOptional<FString> ExternalUrl;
	/* The animation url of the NFT */
	TOptional<FString> AnimationUrl;
	/* The youtube URL of NFT */
	TOptional<FString> YoutubeUrl;
	/* List of Metadata attributes */
	TOptional<TArray<OpenAPINFTMetadataAttribute>> Attributes;
	/* Balance of NFT */
	TOptional<int32> Balance;
};

}
