/**
 * Indexer Marketplace APIs
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace ImmutableIndexerSearchAPI
{

/*
 * OpenAPIChain
 *
 * The chain details
 */
class IMMUTABLEINDEXERSEARCHAPI_API OpenAPIChain : public Model
{
public:
    virtual ~OpenAPIChain() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The id of chain */
	FString Id;
	/* The name of chain */
	FString Name;
};

}
