/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableTsSdkApi_OrderProtocolData.h"

#include "ImmutableTsSdkApiModule.h"
#include "ImmutableTsSdkApi_Helpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

inline FString ToString(const ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum& Value)
{
	switch (Value)
	{
	case ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum::FullRestricted:
		return TEXT("FULL_RESTRICTED");
	case ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum::PartialRestricted:
		return TEXT("PARTIAL_RESTRICTED");
	}

	UE_LOG(LogImmutableTsSdkApi, Error, TEXT("Invalid ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString ImmutableTsSdkApi_OrderProtocolData::EnumToString(const ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum& Value)
{
	static TMap<FString, ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum> StringToEnum = { 
		{ TEXT("FULL_RESTRICTED"), ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum::FullRestricted },
		{ TEXT("PARTIAL_RESTRICTED"), ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum::PartialRestricted }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool ImmutableTsSdkApi_OrderProtocolData::EnumFromString(const FString& EnumAsString, ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, ImmutableTsSdkApi_OrderProtocolData::OrderTypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void ImmutableTsSdkApi_OrderProtocolData::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Counter.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("counter")); WriteJsonValue(Writer, Counter.GetValue());
	}
	if (OrderType.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("orderType")); WriteJsonValue(Writer, OrderType.GetValue());
	}
	if (SeaportAddress.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("seaportAddress")); WriteJsonValue(Writer, SeaportAddress.GetValue());
	}
	if (SeaportVersion.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("seaportVersion")); WriteJsonValue(Writer, SeaportVersion.GetValue());
	}
	if (ZoneAddress.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("zoneAddress")); WriteJsonValue(Writer, ZoneAddress.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ImmutableTsSdkApi_OrderProtocolData::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("counter"), Counter);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("orderType"), OrderType);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("seaportAddress"), SeaportAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("seaportVersion"), SeaportVersion);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("zoneAddress"), ZoneAddress);

	return ParseSuccess;
}

}
