/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableTsSdkApi_V1TsSdkOrderbookCreateListingPostRequest.h"

#include "ImmutableTsSdkApiModule.h"
#include "ImmutableTsSdkApi_Helpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

void ImmutableTsSdkApi_V1TsSdkOrderbookCreateListingPostRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("makerFees")); WriteJsonValue(Writer, MakerFees);
	Writer->WriteIdentifierPrefix(TEXT("orderComponents")); WriteJsonValue(Writer, OrderComponents);
	Writer->WriteIdentifierPrefix(TEXT("orderHash")); WriteJsonValue(Writer, OrderHash);
	Writer->WriteIdentifierPrefix(TEXT("orderSignature")); WriteJsonValue(Writer, OrderSignature);
	Writer->WriteObjectEnd();
}

bool ImmutableTsSdkApi_V1TsSdkOrderbookCreateListingPostRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("makerFees"), MakerFees);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("orderComponents"), OrderComponents);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("orderHash"), OrderHash);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("orderSignature"), OrderSignature);

	return ParseSuccess;
}

}
