/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableTsSdkApi_DefaultApi.h"

#include "ImmutableTsSdkApi_DefaultApiOperations.h"
#include "ImmutableTsSdkApiModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace ImmutableTsSdkApi
{

ImmutableTsSdkApi_DefaultApi::ImmutableTsSdkApi_DefaultApi()
: Url(TEXT("https://api.immutable.com"))
{
}

ImmutableTsSdkApi_DefaultApi::~ImmutableTsSdkApi_DefaultApi() {}

void ImmutableTsSdkApi_DefaultApi::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void ImmutableTsSdkApi_DefaultApi::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void ImmutableTsSdkApi_DefaultApi::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool ImmutableTsSdkApi_DefaultApi::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogImmutableTsSdkApi, Error, TEXT("ImmutableTsSdkApi_DefaultApi: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void ImmutableTsSdkApi_DefaultApi::SetHttpRetryManager(FHttpRetrySystem::FManager& InRetryManager)
{
	if (RetryManager != &InRetryManager)
	{
		DefaultRetryManager.Reset();
		RetryManager = &InRetryManager;
	}
}

FHttpRetrySystem::FManager& ImmutableTsSdkApi_DefaultApi::GetHttpRetryManager()
{
	checkf(RetryManager, TEXT("ImmutableTsSdkApi_DefaultApi: RetryManager is null.  You may have meant to set it with SetHttpRetryManager first, or you may not be using a custom RetryManager at all."))
	return *RetryManager;
}

FHttpRequestRef ImmutableTsSdkApi_DefaultApi::CreateHttpRequest(const Request& Request) const
{
	if (!Request.GetRetryParams().IsSet())
	{
		return FHttpModule::Get().CreateRequest();
	}
	else
	{
		if (!RetryManager)
		{
			// Create default retry manager if none was specified
			DefaultRetryManager = MakeUnique<HttpRetryManager>(6, 60);
			RetryManager = DefaultRetryManager.Get();
		}

		const HttpRetryParams& Params = Request.GetRetryParams().GetValue();
		return RetryManager->CreateRequest(Params.RetryLimitCountOverride, Params.RetryTimeoutRelativeSecondsOverride, Params.RetryResponseCodes, Params.RetryVerbs, Params.RetryDomains);
	}
}

void ImmutableTsSdkApi_DefaultApi::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty())
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogImmutableTsSdkApi, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1HeartbeatGet(const V1HeartbeatGetRequest& Request, const FV1HeartbeatGetDelegate& Delegate /*= FV1HeartbeatGetDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1HeartbeatGetResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1HeartbeatGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1HeartbeatGetDelegate Delegate) const
{
	V1HeartbeatGetResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1HeartbeatHead(const V1HeartbeatHeadRequest& Request, const FV1HeartbeatHeadDelegate& Delegate /*= FV1HeartbeatHeadDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1HeartbeatHeadResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1HeartbeatHeadResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1HeartbeatHeadDelegate Delegate) const
{
	V1HeartbeatHeadResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCancelOrdersOnChainPost(const V1TsSdkOrderbookCancelOrdersOnChainPostRequest& Request, const FV1TsSdkOrderbookCancelOrdersOnChainPostDelegate& Delegate /*= FV1TsSdkOrderbookCancelOrdersOnChainPostDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookCancelOrdersOnChainPostResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookCancelOrdersOnChainPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkOrderbookCancelOrdersOnChainPostDelegate Delegate) const
{
	V1TsSdkOrderbookCancelOrdersOnChainPostResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCancelOrdersPost(const V1TsSdkOrderbookCancelOrdersPostRequest& Request, const FV1TsSdkOrderbookCancelOrdersPostDelegate& Delegate /*= FV1TsSdkOrderbookCancelOrdersPostDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookCancelOrdersPostResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookCancelOrdersPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkOrderbookCancelOrdersPostDelegate Delegate) const
{
	V1TsSdkOrderbookCancelOrdersPostResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCreateListingPost(const V1TsSdkOrderbookCreateListingPostRequest& Request, const FV1TsSdkOrderbookCreateListingPostDelegate& Delegate /*= FV1TsSdkOrderbookCreateListingPostDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookCreateListingPostResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookCreateListingPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkOrderbookCreateListingPostDelegate Delegate) const
{
	V1TsSdkOrderbookCreateListingPostResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookFulfillOrderPost(const V1TsSdkOrderbookFulfillOrderPostRequest& Request, const FV1TsSdkOrderbookFulfillOrderPostDelegate& Delegate /*= FV1TsSdkOrderbookFulfillOrderPostDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookFulfillOrderPostResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookFulfillOrderPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkOrderbookFulfillOrderPostDelegate Delegate) const
{
	V1TsSdkOrderbookFulfillOrderPostResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookPrepareListingPost(const V1TsSdkOrderbookPrepareListingPostRequest& Request, const FV1TsSdkOrderbookPrepareListingPostDelegate& Delegate /*= FV1TsSdkOrderbookPrepareListingPostDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookPrepareListingPostResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookPrepareListingPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkOrderbookPrepareListingPostDelegate Delegate) const
{
	V1TsSdkOrderbookPrepareListingPostResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookPrepareOrderCancellationsPost(const V1TsSdkOrderbookPrepareOrderCancellationsPostRequest& Request, const FV1TsSdkOrderbookPrepareOrderCancellationsPostDelegate& Delegate /*= FV1TsSdkOrderbookPrepareOrderCancellationsPostDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookPrepareOrderCancellationsPostResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkOrderbookPrepareOrderCancellationsPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkOrderbookPrepareOrderCancellationsPostDelegate Delegate) const
{
	V1TsSdkOrderbookPrepareOrderCancellationsPostResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkTokenBalanceGet(const V1TsSdkTokenBalanceGetRequest& Request, const FV1TsSdkTokenBalanceGetDelegate& Delegate /*= FV1TsSdkTokenBalanceGetDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkTokenBalanceGetResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkTokenBalanceGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkTokenBalanceGetDelegate Delegate) const
{
	V1TsSdkTokenBalanceGetResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ImmutableTsSdkApi_DefaultApi::V1TsSdkTokenBalanceHead(const V1TsSdkTokenBalanceHeadRequest& Request, const FV1TsSdkTokenBalanceHeadDelegate& Delegate /*= FV1TsSdkTokenBalanceHeadDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ImmutableTsSdkApi_DefaultApi::OnV1TsSdkTokenBalanceHeadResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ImmutableTsSdkApi_DefaultApi::OnV1TsSdkTokenBalanceHeadResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FV1TsSdkTokenBalanceHeadDelegate Delegate) const
{
	V1TsSdkTokenBalanceHeadResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

}
