/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableTsSdkApi_TransactionPurpose.h"

#include "ImmutableTsSdkApiModule.h"
#include "ImmutableTsSdkApi_Helpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

inline FString ToString(const ImmutableTsSdkApi_TransactionPurpose::Values& Value)
{
	switch (Value)
	{
	case ImmutableTsSdkApi_TransactionPurpose::Values::Approval:
		return TEXT("APPROVAL");
	case ImmutableTsSdkApi_TransactionPurpose::Values::FulfillOrder:
		return TEXT("FULFILL_ORDER");
	case ImmutableTsSdkApi_TransactionPurpose::Values::Cancel:
		return TEXT("CANCEL");
	}

	UE_LOG(LogImmutableTsSdkApi, Error, TEXT("Invalid ImmutableTsSdkApi_TransactionPurpose::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString ImmutableTsSdkApi_TransactionPurpose::EnumToString(const ImmutableTsSdkApi_TransactionPurpose::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, ImmutableTsSdkApi_TransactionPurpose::Values& Value)
{
	static TMap<FString, ImmutableTsSdkApi_TransactionPurpose::Values> StringToEnum = { 
		{ TEXT("APPROVAL"), ImmutableTsSdkApi_TransactionPurpose::Values::Approval },
		{ TEXT("FULFILL_ORDER"), ImmutableTsSdkApi_TransactionPurpose::Values::FulfillOrder },
		{ TEXT("CANCEL"), ImmutableTsSdkApi_TransactionPurpose::Values::Cancel }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool ImmutableTsSdkApi_TransactionPurpose::EnumFromString(const FString& EnumAsString, ImmutableTsSdkApi_TransactionPurpose::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const ImmutableTsSdkApi_TransactionPurpose::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, ImmutableTsSdkApi_TransactionPurpose::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void ImmutableTsSdkApi_TransactionPurpose::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool ImmutableTsSdkApi_TransactionPurpose::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
