/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest.h"

#include "ImmutableTsSdkApiModule.h"
#include "ImmutableTsSdkApi_Helpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

void ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("listingId")); WriteJsonValue(Writer, ListingId);
	Writer->WriteIdentifierPrefix(TEXT("takerAddress")); WriteJsonValue(Writer, TakerAddress);
	Writer->WriteIdentifierPrefix(TEXT("takerFees")); WriteJsonValue(Writer, TakerFees);
	if (AmountToFill.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("amountToFill")); WriteJsonValue(Writer, AmountToFill.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("listingId"), ListingId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("takerAddress"), TakerAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("takerFees"), TakerFees);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("amountToFill"), AmountToFill);

	return ParseSuccess;
}

}
