/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableTsSdkApiModule.h"

IMPLEMENT_MODULE(ImmutableTsSdkApiModule, ImmutableTsSdkApi);
DEFINE_LOG_CATEGORY(LogImmutableTsSdkApi);

void ImmutableTsSdkApiModule::StartupModule()
{
}

void ImmutableTsSdkApiModule::ShutdownModule()
{
}
