/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIOrderStatus.h"

#include "ImmutableTsSdkApiModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

inline FString ToString(const OpenAPIOrderStatus::NameEnum& Value)
{
	switch (Value)
	{
	case OpenAPIOrderStatus::NameEnum::Pending:
		return TEXT("PENDING");
	}

	UE_LOG(LogImmutableTsSdkApi, Error, TEXT("Invalid OpenAPIOrderStatus::NameEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIOrderStatus::EnumToString(const OpenAPIOrderStatus::NameEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIOrderStatus::NameEnum& Value)
{
	static TMap<FString, OpenAPIOrderStatus::NameEnum> StringToEnum = { 
		{ TEXT("PENDING"), OpenAPIOrderStatus::NameEnum::Pending }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIOrderStatus::EnumFromString(const FString& EnumAsString, OpenAPIOrderStatus::NameEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIOrderStatus::NameEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIOrderStatus::NameEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIOrderStatus::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Name.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name.GetValue());
	}
	if (CancellationType.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("cancellation_type")); WriteJsonValue(Writer, CancellationType.GetValue());
	}
	if (Pending.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("pending")); WriteJsonValue(Writer, Pending.GetValue());
	}
	if (SufficientApprovals.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("sufficient_approvals")); WriteJsonValue(Writer, SufficientApprovals.GetValue());
	}
	if (SufficientBalances.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("sufficient_balances")); WriteJsonValue(Writer, SufficientBalances.GetValue());
	}
	if (Evaluated.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("evaluated")); WriteJsonValue(Writer, Evaluated.GetValue());
	}
	if (Started.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("started")); WriteJsonValue(Writer, Started.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIOrderStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("cancellation_type"), CancellationType);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("pending"), Pending);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sufficient_approvals"), SufficientApprovals);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sufficient_balances"), SufficientBalances);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("evaluated"), Evaluated);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("started"), Started);

	return ParseSuccess;
}

}
