/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICancellationType.h"

#include "ImmutableTsSdkApiModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

inline FString ToString(const OpenAPICancellationType::Values& Value)
{
	switch (Value)
	{
	case OpenAPICancellationType::Values::OnChain:
		return TEXT("ON_CHAIN");
	case OpenAPICancellationType::Values::OffChain:
		return TEXT("OFF_CHAIN");
	case OpenAPICancellationType::Values::Underfunded:
		return TEXT("UNDERFUNDED");
	}

	UE_LOG(LogImmutableTsSdkApi, Error, TEXT("Invalid OpenAPICancellationType::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPICancellationType::EnumToString(const OpenAPICancellationType::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPICancellationType::Values& Value)
{
	static TMap<FString, OpenAPICancellationType::Values> StringToEnum = { 
		{ TEXT("ON_CHAIN"), OpenAPICancellationType::Values::OnChain },
		{ TEXT("OFF_CHAIN"), OpenAPICancellationType::Values::OffChain },
		{ TEXT("UNDERFUNDED"), OpenAPICancellationType::Values::Underfunded }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPICancellationType::EnumFromString(const FString& EnumAsString, OpenAPICancellationType::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPICancellationType::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPICancellationType::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPICancellationType::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPICancellationType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
