/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICancelOrders200ResponseResultFailedCancellationsInner.h"

#include "ImmutableTsSdkApiModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

inline FString ToString(const OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum& Value)
{
	switch (Value)
	{
	case OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum::Filled:
		return TEXT("FILLED");
	}

	UE_LOG(LogImmutableTsSdkApi, Error, TEXT("Invalid OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPICancelOrders200ResponseResultFailedCancellationsInner::EnumToString(const OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum& Value)
{
	static TMap<FString, OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum> StringToEnum = { 
		{ TEXT("FILLED"), OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum::Filled }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPICancelOrders200ResponseResultFailedCancellationsInner::EnumFromString(const FString& EnumAsString, OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPICancelOrders200ResponseResultFailedCancellationsInner::ReasonCodeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPICancelOrders200ResponseResultFailedCancellationsInner::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Order.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("order")); WriteJsonValue(Writer, Order.GetValue());
	}
	if (ReasonCode.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("reason_code")); WriteJsonValue(Writer, ReasonCode.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPICancelOrders200ResponseResultFailedCancellationsInner::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("order"), Order);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("reason_code"), ReasonCode);

	return ParseSuccess;
}

}
