/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIItemType.h"

#include "ImmutableTsSdkApiModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableTsSdkApi
{

void OpenAPIItemType::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteValue(Value);
}

bool OpenAPIItemType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return JsonValue->TryGetNumber(Value);
}

}
