/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"

namespace ImmutableTsSdkApi
{

/*
 * ImmutableTsSdkApi_ERC1155Item
 *
 * 
 */
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_ERC1155Item : public Model
{
public:
    virtual ~ImmutableTsSdkApi_ERC1155Item() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Amount;
	FString ContractAddress;
	FString TokenId;
	enum class TypeEnum
	{
		ERC1155,
  	};

	static FString EnumToString(const TypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TypeEnum& EnumValue);
	TypeEnum Type;
};

}
