/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPost200ResponseResult.h"

namespace ImmutableTsSdkApi
{

/*
 * ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPost200Response
 *
 * Response schema for the cancelOrder endpoint
 */
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPost200Response : public Model
{
public:
    virtual ~ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPost200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPost200ResponseResult> Result;
};

}
