/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequestTakerFeesInner.h"

namespace ImmutableTsSdkApi
{

/*
 * ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest
 *
 * 
 */
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest : public Model
{
public:
    virtual ~ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* listingId */
	FString ListingId;
	/* takerAddress */
	FString TakerAddress;
	/* takerFees */
	TArray<ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequestTakerFeesInner> TakerFees;
	/* amountToFill */
	TOptional<FString> AmountToFill;
};

}
