/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"

namespace ImmutableTsSdkApi
{

/*
 * ImmutableTsSdkApi_OrderStatusOneOf5
 *
 * 
 */
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_OrderStatusOneOf5 : public Model
{
public:
    virtual ~ImmutableTsSdkApi_OrderStatusOneOf5() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Whether the order has been evaluated after its creation */
	TOptional<bool> Evaluated;
	enum class NameEnum
	{
		Pending,
  	};

	static FString EnumToString(const NameEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, NameEnum& EnumValue);
	/* The order status that indicates the order is yet to be active due to various reasons. */
	TOptional<NameEnum> Name;
	/* Whether the order has reached its specified start time */
	TOptional<bool> Started;
};

}
