/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"
#include "ImmutableTsSdkApi_CancellationType.h"
#include "ImmutableTsSdkApi_OrderStatusOneOf.h"
#include "ImmutableTsSdkApi_OrderStatusOneOf1.h"
#include "ImmutableTsSdkApi_OrderStatusOneOf2.h"
#include "ImmutableTsSdkApi_OrderStatusOneOf3.h"
#include "ImmutableTsSdkApi_OrderStatusOneOf4.h"
#include "ImmutableTsSdkApi_OrderStatusOneOf5.h"

namespace ImmutableTsSdkApi
{

/*
 * ImmutableTsSdkApi_OrderStatus
 *
 * The Order status
 */
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_OrderStatus : public Model
{
public:
    virtual ~ImmutableTsSdkApi_OrderStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class NameEnum
	{
		Pending,
  	};

	static FString EnumToString(const NameEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, NameEnum& EnumValue);
	/* The order status that indicates the order is yet to be active due to various reasons. */
	TOptional<NameEnum> Name;
	TOptional<ImmutableTsSdkApi_CancellationType> CancellationType;
	/* Whether the cancellation of the order is pending */
	TOptional<bool> Pending;
	/* Whether the order offerer has sufficient approvals */
	TOptional<bool> SufficientApprovals;
	/* Whether the order offerer still has sufficient balance to complete the order */
	TOptional<bool> SufficientBalances;
	/* Whether the order has been evaluated after its creation */
	TOptional<bool> Evaluated;
	/* Whether the order has reached its specified start time */
	TOptional<bool> Started;
};

}
