/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequestBuy.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequestSell.h"

namespace ImmutableTsSdkApi
{

/*
 * ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequest
 *
 * 
 */
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequest : public Model
{
public:
    virtual ~ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequestBuy Buy;
	FString MakerAddress;
	TOptional<FDateTime> OrderExpiry;
	ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequestSell Sell;
};

}
