/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"
#include "ImmutableTsSdkApi_DefaultApi.h"

#include "ImmutableTsSdkApi_V1HeartbeatGet200Response.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersOnChainPost200Response.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersOnChainPostRequest.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPost200Response.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPostRequest.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookCreateListingPost200Response.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookCreateListingPostRequest.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPost200Response.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPost200Response.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequest.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookPrepareOrderCancellationsPost200Response.h"
#include "ImmutableTsSdkApi_V1TsSdkOrderbookPrepareOrderCancellationsPostRequest.h"
#include "ImmutableTsSdkApi_V1TsSdkTokenBalanceGet200Response.h"

namespace ImmutableTsSdkApi
{

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1HeartbeatGetRequest : public Request
{
public:
    virtual ~V1HeartbeatGetRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1HeartbeatGetResponse : public Response
{
public:
    virtual ~V1HeartbeatGetResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1HeartbeatGet200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1HeartbeatHeadRequest : public Request
{
public:
    virtual ~V1HeartbeatHeadRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1HeartbeatHeadResponse : public Response
{
public:
    virtual ~V1HeartbeatHeadResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1HeartbeatGet200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCancelOrdersOnChainPostRequest : public Request
{
public:
    virtual ~V1TsSdkOrderbookCancelOrdersOnChainPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersOnChainPostRequest> ImmutableTsSdkApiV1TsSdkOrderbookCancelOrdersOnChainPostRequest;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCancelOrdersOnChainPostResponse : public Response
{
public:
    virtual ~V1TsSdkOrderbookCancelOrdersOnChainPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersOnChainPost200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCancelOrdersPostRequest : public Request
{
public:
    virtual ~V1TsSdkOrderbookCancelOrdersPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPostRequest> ImmutableTsSdkApiV1TsSdkOrderbookCancelOrdersPostRequest;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCancelOrdersPostResponse : public Response
{
public:
    virtual ~V1TsSdkOrderbookCancelOrdersPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkOrderbookCancelOrdersPost200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCreateListingPostRequest : public Request
{
public:
    virtual ~V1TsSdkOrderbookCreateListingPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<ImmutableTsSdkApi_V1TsSdkOrderbookCreateListingPostRequest> ImmutableTsSdkApiV1TsSdkOrderbookCreateListingPostRequest;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookCreateListingPostResponse : public Response
{
public:
    virtual ~V1TsSdkOrderbookCreateListingPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkOrderbookCreateListingPost200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookFulfillOrderPostRequest : public Request
{
public:
    virtual ~V1TsSdkOrderbookFulfillOrderPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPostRequest> ImmutableTsSdkApiV1TsSdkOrderbookFulfillOrderPostRequest;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookFulfillOrderPostResponse : public Response
{
public:
    virtual ~V1TsSdkOrderbookFulfillOrderPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkOrderbookFulfillOrderPost200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookPrepareListingPostRequest : public Request
{
public:
    virtual ~V1TsSdkOrderbookPrepareListingPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPostRequest> ImmutableTsSdkApiV1TsSdkOrderbookPrepareListingPostRequest;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookPrepareListingPostResponse : public Response
{
public:
    virtual ~V1TsSdkOrderbookPrepareListingPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkOrderbookPrepareListingPost200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookPrepareOrderCancellationsPostRequest : public Request
{
public:
    virtual ~V1TsSdkOrderbookPrepareOrderCancellationsPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<ImmutableTsSdkApi_V1TsSdkOrderbookPrepareOrderCancellationsPostRequest> ImmutableTsSdkApiV1TsSdkOrderbookPrepareOrderCancellationsPostRequest;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkOrderbookPrepareOrderCancellationsPostResponse : public Response
{
public:
    virtual ~V1TsSdkOrderbookPrepareOrderCancellationsPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkOrderbookPrepareOrderCancellationsPost200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkTokenBalanceGetRequest : public Request
{
public:
    virtual ~V1TsSdkTokenBalanceGetRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString WalletAddress;
	FString ContractAddress;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkTokenBalanceGetResponse : public Response
{
public:
    virtual ~V1TsSdkTokenBalanceGetResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkTokenBalanceGet200Response Content;
};

/* 

*/
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkTokenBalanceHeadRequest : public Request
{
public:
    virtual ~V1TsSdkTokenBalanceHeadRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString WalletAddress;
	FString ContractAddress;
};

class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_DefaultApi::V1TsSdkTokenBalanceHeadResponse : public Response
{
public:
    virtual ~V1TsSdkTokenBalanceHeadResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ImmutableTsSdkApi_V1TsSdkTokenBalanceGet200Response Content;
};

}
