/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ImmutableTsSdkApi_BaseModel.h"
#include "ImmutableTsSdkApi_SignableActionMessage.h"
#include "ImmutableTsSdkApi_SignablePurpose.h"

namespace ImmutableTsSdkApi
{

/*
 * ImmutableTsSdkApi_SignableAction
 *
 * 
 */
class IMMUTABLETSSDKAPI_API ImmutableTsSdkApi_SignableAction : public Model
{
public:
    virtual ~ImmutableTsSdkApi_SignableAction() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<ImmutableTsSdkApi_SignableActionMessage> Message;
	TOptional<ImmutableTsSdkApi_SignablePurpose> Purpose;
	enum class TypeEnum
	{
		Signable,
  	};

	static FString EnumToString(const TypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TypeEnum& EnumValue);
	TypeEnum Type;
};

}
