/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPISignableActionMessage.h"
#include "OpenAPISignablePurpose.h"

namespace ImmutableTsSdkApi
{

/*
 * OpenAPISignableAction
 *
 * 
 */
class IMMUTABLETSSDKAPI_API OpenAPISignableAction : public Model
{
public:
    virtual ~OpenAPISignableAction() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPISignableActionMessage> Message;
	TOptional<OpenAPISignablePurpose> Purpose;
	enum class TypeEnum
	{
		Signable,
  	};

	static FString EnumToString(const TypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TypeEnum& EnumValue);
	TypeEnum Type;
};

}
