/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIAction.h"
#include "OpenAPIOrderComponents.h"

namespace ImmutableTsSdkApi
{

/*
 * OpenAPIPrepareListing200Response
 *
 * Response schema for the prepareListing endpoint
 */
class IMMUTABLETSSDKAPI_API OpenAPIPrepareListing200Response : public Model
{
public:
    virtual ~OpenAPIPrepareListing200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<OpenAPIAction> Actions;
	OpenAPIOrderComponents OrderComponents;
	FString OrderHash;
};

}
