/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPICancellationType.h"

namespace ImmutableTsSdkApi
{

/*
 * OpenAPIOrderStatusOneOf1
 *
 * 
 */
class IMMUTABLETSSDKAPI_API OpenAPIOrderStatusOneOf1 : public Model
{
public:
    virtual ~OpenAPIOrderStatusOneOf1() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPICancellationType> CancellationType;
	enum class NameEnum
	{
		Cancelled,
  	};

	static FString EnumToString(const NameEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, NameEnum& EnumValue);
	/* The order status indicating a order is has been cancelled or about to be cancelled. */
	TOptional<NameEnum> Name;
	/* Whether the cancellation of the order is pending */
	TOptional<bool> Pending;
};

}
