/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIFee.h"
#include "OpenAPIOrderChain.h"
#include "OpenAPIOrderFillStatus.h"
#include "OpenAPIOrderProtocolData.h"
#include "OpenAPIOrderStatus.h"
#include "OpenAPIPrepareListingRequestBuy.h"
#include "OpenAPIPrepareListingRequestSell.h"

namespace ImmutableTsSdkApi
{

/*
 * OpenAPIOrder
 *
 * 
 */
class IMMUTABLETSSDKAPI_API OpenAPIOrder : public Model
{
public:
    virtual ~OpenAPIOrder() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> AccountAddress;
	TOptional<TArray<OpenAPIPrepareListingRequestBuy>> Buy;
	TOptional<OpenAPIOrderChain> Chain;
	TOptional<FString> CreatedAt;
	/* Time after which the Order is expired */
	TOptional<FString> EndAt;
	TOptional<TArray<OpenAPIFee>> Fees;
	TOptional<OpenAPIOrderFillStatus> FillStatus;
	FString Id;
	FString OrderHash;
	TOptional<OpenAPIOrderProtocolData> ProtocolData;
	TOptional<FString> Salt;
	TArray<OpenAPIPrepareListingRequestSell> Sell;
	FString Signature;
	/* Time after which the Order is considered active */
	FString StartAt;
	OpenAPIOrderStatus Status;
	enum class TypeEnum
	{
		Listing,
  	};

	static FString EnumToString(const TypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TypeEnum& EnumValue);
	TypeEnum Type;
	FString UpdatedAt;
};

}
