/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIOrderComponentsConsiderationInner.h"
#include "OpenAPIOrderComponentsOfferInner.h"
#include "OpenAPIOrderType.h"

namespace ImmutableTsSdkApi
{

/*
 * OpenAPIOrderComponents
 *
 * 
 */
class IMMUTABLETSSDKAPI_API OpenAPIOrderComponents : public Model
{
public:
    virtual ~OpenAPIOrderComponents() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString ConduitKey;
	TArray<OpenAPIOrderComponentsConsiderationInner> Consideration;
	FString EndTime;
	TArray<OpenAPIOrderComponentsOfferInner> Offer;
	FString Offerer;
	OpenAPIOrderType OrderType;
	FString Salt;
	FString StartTime;
	FString TotalOriginalConsiderationItems;
	FString Zone;
	FString ZoneHash;
	FString Counter;
};

}
