/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIOrder.h"

namespace ImmutableTsSdkApi
{

/*
 * OpenAPICreateListing200Response
 *
 * The response schema for the create listing endpoint
 */
class IMMUTABLETSSDKAPI_API OpenAPICreateListing200Response : public Model
{
public:
    virtual ~OpenAPICreateListing200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIOrder> Result;
};

}
