/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPICollectionsApi.h"

#include "OpenAPIAPIError400.h"
#include "OpenAPIAPIError401.h"
#include "OpenAPIAPIError403.h"
#include "OpenAPIAPIError404.h"
#include "OpenAPIAPIError500.h"
#include "OpenAPIAssetVerificationStatus.h"
#include "OpenAPIGetCollectionResult.h"
#include "OpenAPIListCollectionsResult.h"
#include "OpenAPIRefreshCollectionMetadataRequest.h"
#include "OpenAPIRefreshCollectionMetadataResult.h"

namespace ImmutableOpenAPI
{

/* Get collection by contract address
 *
 * Get collection by contract address
*/
class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::GetCollectionRequest : public Request
{
public:
    virtual ~GetCollectionRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
};

class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::GetCollectionResponse : public Response
{
public:
    virtual ~GetCollectionResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIGetCollectionResult Content;
};

/* List all collections
 *
 * List all collections
*/
class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::ListCollectionsRequest : public Request
{
public:
    virtual ~ListCollectionsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* List of contract addresses to filter by */
	TOptional<TArray<FString>> ContractAddress;
	/* List of verification status to filter by */
	TOptional<TArray<OpenAPIAssetVerificationStatus>> VerificationStatus;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::ListCollectionsResponse : public Response
{
public:
    virtual ~ListCollectionsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListCollectionsResult Content;
};

/* List collections by NFT owner
 *
 * List collections by NFT owner account address
*/
class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::ListCollectionsByNFTOwnerRequest : public Request
{
public:
    virtual ~ListCollectionsByNFTOwnerRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Account address */
	FString AccountAddress;
	/* The name of chain */
	FString ChainName;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::ListCollectionsByNFTOwnerResponse : public Response
{
public:
    virtual ~ListCollectionsByNFTOwnerResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListCollectionsResult Content;
};

/* Refresh collection metadata
 *
 * Refresh collection metadata
*/
class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::RefreshCollectionMetadataRequest : public Request
{
public:
    virtual ~RefreshCollectionMetadataRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
	/* The request body */
	OpenAPIRefreshCollectionMetadataRequest OpenAPIRefreshCollectionMetadataRequest;
};

class IMMUTABLEOPENAPI_API OpenAPICollectionsApi::RefreshCollectionMetadataResponse : public Response
{
public:
    virtual ~RefreshCollectionMetadataResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIRefreshCollectionMetadataResult Content;
};

}
