/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIOperatorAllowlistStatusRequested.h"
#include "OpenAPIOperatorAllowlistStatusUpdated.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIOperatorAllowlistStatusDetails
 *
 * The operator allowlist status details
 */
class IMMUTABLEOPENAPI_API OpenAPIOperatorAllowlistStatusDetails : public Model
{
public:
    virtual ~OpenAPIOperatorAllowlistStatusDetails() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Reason this contract needs to be added */
	FString Purpose;
	/* Attestation of whether this contract is a settlement contract */
	bool IsSettlementContract = false;
	/* Why this action was performed */
	FString Reason;
};

}
