/**
 * Indexer Search API
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIAPIError409AllOf
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPIAPIError409AllOf : public Model
{
public:
    virtual ~OpenAPIAPIError409AllOf() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class CodeEnum
	{
		ConflictError,
  	};

	static FString EnumToString(const CodeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, CodeEnum& EnumValue);
	/* Error Code */
	CodeEnum Code;
	/* Additional details to help resolve the error */
	TOptional<TMap<FString, TSharedPtr<FJsonValue>>> Details;
};

}
