/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPICall.h"
#include "OpenAPISignCraftingRequestMultiCaller.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPISignCraftingRequest
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPISignCraftingRequest : public Model
{
public:
    virtual ~OpenAPISignCraftingRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPISignCraftingRequestMultiCaller MultiCaller;
	/* The id of this request in the system that originates the crafting request, specified as a 32 byte hex string */
	FString ReferenceId;
	/* The calls to be signed */
	TArray<OpenAPICall> Calls;
	/* The expiration time of the request */
	FDateTime ExpiresAt;
};

}
