/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIMetadata.h"
#include "OpenAPIPage.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIListMetadataResult
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPIListMetadataResult : public Model
{
public:
    virtual ~OpenAPIListMetadataResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of metadata */
	TArray<OpenAPIMetadata> Result;
	OpenAPIPage Page;
};

}
