/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPINFTWithBalance.h"
#include "OpenAPIPage.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIListNFTsByOwnerResult
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPIListNFTsByOwnerResult : public Model
{
public:
    virtual ~OpenAPIListNFTsByOwnerResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of NFTs by owner */
	TArray<OpenAPINFTWithBalance> Result;
	OpenAPIPage Page;
};

}
