/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIFulfillableOrder.h"
#include "OpenAPIUnfulfillableOrder.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIFulfillmentData200ResponseResult
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPIFulfillmentData200ResponseResult : public Model
{
public:
    virtual ~OpenAPIFulfillmentData200ResponseResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<OpenAPIFulfillableOrder> FulfillableOrders;
	TArray<OpenAPIUnfulfillableOrder> UnfulfillableOrders;
};

}
