/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIPaymentAmount
 *
 * Amount details
 */
class IMMUTABLEOPENAPI_API OpenAPIPaymentAmount : public Model
{
public:
    virtual ~OpenAPIPaymentAmount() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The token amount value. This value is provided in the smallest unit of the token (e.g. wei for ETH) */
	FString Value;
	/* The token amount value in ETH */
	FString ValueInEth;
};

}
