/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIPage
 *
 * Pagination properties
 */
class IMMUTABLEOPENAPI_API OpenAPIPage : public Model
{
public:
    virtual ~OpenAPIPage() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* First item as an encoded string */
	TOptional<FString> PreviousCursor;
	/* Last item as an encoded string */
	TOptional<FString> NextCursor;
};

}
