/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPassportApi.h"

#include "OpenAPIAPIError400.h"
#include "OpenAPIAPIError401.h"
#include "OpenAPIAPIError403.h"
#include "OpenAPIAPIError429.h"
#include "OpenAPIAPIError500.h"
#include "OpenAPIBasicAPIError.h"
#include "OpenAPIGetLinkedAddressesRes.h"

namespace ImmutableOpenAPI
{

/* Get Ethereum linked addresses for a user
 *
 * This API has been deprecated, please use https://docs.immutable.com/zkevm/api/reference/#/operations/getUserInfo instead to get a list of linked addresses.
*/
class IMMUTABLEOPENAPI_API OpenAPIPassportApi::GetLinkedAddressesRequest : public Request
{
public:
    virtual ~GetLinkedAddressesRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The user's userId */
	FString UserId;
	FString ChainName;
};

class IMMUTABLEOPENAPI_API OpenAPIPassportApi::GetLinkedAddressesResponse : public Response
{
public:
    virtual ~GetLinkedAddressesResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIGetLinkedAddressesRes Content;
};

}
