/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIMetadataApi.h"

#include "OpenAPIAPIError400.h"
#include "OpenAPIAPIError401.h"
#include "OpenAPIAPIError403.h"
#include "OpenAPIAPIError404.h"
#include "OpenAPIAPIError429.h"
#include "OpenAPIAPIError500.h"
#include "OpenAPIGetMetadataResult.h"
#include "OpenAPIListMetadataResult.h"
#include "OpenAPIMetadataRefreshRateLimitResult.h"
#include "OpenAPIRefreshMetadataByIDRequest.h"
#include "OpenAPIRefreshNFTMetadataByTokenIDRequest.h"

namespace ImmutableOpenAPI
{

/* Get metadata by ID
 *
 * Get metadata by ID
*/
class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::GetMetadataRequest : public Request
{
public:
    virtual ~GetMetadataRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* The address of metadata contract */
	FString ContractAddress;
	/* The id of the metadata */
	FGuid MetadataId;
};

class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::GetMetadataResponse : public Response
{
public:
    virtual ~GetMetadataResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIGetMetadataResult Content;
};

/* Get a list of metadata from the given contract
 *
 * Get a list of metadata from the given contract
*/
class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::ListMetadataRequest : public Request
{
public:
    virtual ~ListMetadataRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* The address of metadata contract */
	FString ContractAddress;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::ListMetadataResponse : public Response
{
public:
    virtual ~ListMetadataResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListMetadataResult Content;
};

/* Get a list of metadata from the given chain
 *
 * Get a list of metadata from the given chain
*/
class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::ListMetadataForChainRequest : public Request
{
public:
    virtual ~ListMetadataForChainRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::ListMetadataForChainResponse : public Response
{
public:
    virtual ~ListMetadataForChainResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListMetadataResult Content;
};

/* Refresh stacked metadata
 *
 * Refresh stacked metadata
*/
class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::RefreshMetadataByIDRequest : public Request
{
public:
    virtual ~RefreshMetadataByIDRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* Contract address */
	FString ContractAddress;
	/* NFT Metadata Refresh Request */
	OpenAPIRefreshMetadataByIDRequest OpenAPIRefreshMetadataByIDRequest;
};

class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::RefreshMetadataByIDResponse : public Response
{
public:
    virtual ~RefreshMetadataByIDResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIMetadataRefreshRateLimitResult Content;
};

/* Refresh NFT metadata
 *
 * Refresh NFT metadata
*/
class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::RefreshNFTMetadataByTokenIDRequest : public Request
{
public:
    virtual ~RefreshNFTMetadataByTokenIDRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
	/* the request body */
	OpenAPIRefreshNFTMetadataByTokenIDRequest OpenAPIRefreshNFTMetadataByTokenIDRequest;
};

class IMMUTABLEOPENAPI_API OpenAPIMetadataApi::RefreshNFTMetadataByTokenIDResponse : public Response
{
public:
    virtual ~RefreshNFTMetadataByTokenIDResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIMetadataRefreshRateLimitResult Content;
};

}
