/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIChain.h"
#include "OpenAPIMarket.h"
#include "OpenAPIMarketNft.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPINFTQuoteResult
 *
 * NFT quote result
 */
class IMMUTABLEOPENAPI_API OpenAPINFTQuoteResult : public Model
{
public:
    virtual ~OpenAPINFTQuoteResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPIChain Chain;
	/* Token id of NFT (uint256 as string) */
	FString TokenId;
	OpenAPIMarket MarketStack;
	OpenAPIMarketNft MarketNft;
	OpenAPIMarket MarketCollection;
};

}
