/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPINftsApi.h"

#include "OpenAPIAPIError400.h"
#include "OpenAPIAPIError401.h"
#include "OpenAPIAPIError403.h"
#include "OpenAPIAPIError404.h"
#include "OpenAPIAPIError409.h"
#include "OpenAPIAPIError429.h"
#include "OpenAPIAPIError500.h"
#include "OpenAPICreateMintRequestRequest.h"
#include "OpenAPICreateMintRequestResult.h"
#include "OpenAPIGetNFTResult.h"
#include "OpenAPIListMintRequestsResult.h"
#include "OpenAPIListNFTsByOwnerResult.h"
#include "OpenAPIListNFTsResult.h"
#include "OpenAPIMintRequestStatus.h"

namespace ImmutableOpenAPI
{

/* Mint NFTs
 *
 * Create a mint request to mint a set of NFTs for a given collection
*/
class IMMUTABLEOPENAPI_API OpenAPINftsApi::CreateMintRequestRequest : public Request
{
public:
    virtual ~CreateMintRequestRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
	/* Create Mint Request Body */
	OpenAPICreateMintRequestRequest OpenAPICreateMintRequestRequest;
};

class IMMUTABLEOPENAPI_API OpenAPINftsApi::CreateMintRequestResponse : public Response
{
public:
    virtual ~CreateMintRequestResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPICreateMintRequestResult Content;
};

/* Get mint request by reference ID
 *
 * Retrieve the status of a mint request identified by its reference_id
*/
class IMMUTABLEOPENAPI_API OpenAPINftsApi::GetMintRequestRequest : public Request
{
public:
    virtual ~GetMintRequestRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
	/* The id of the mint request */
	FString ReferenceId;
};

class IMMUTABLEOPENAPI_API OpenAPINftsApi::GetMintRequestResponse : public Response
{
public:
    virtual ~GetMintRequestResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListMintRequestsResult Content;
};

/* Get NFT by token ID
 *
 * Get NFT by token ID
*/
class IMMUTABLEOPENAPI_API OpenAPINftsApi::GetNFTRequest : public Request
{
public:
    virtual ~GetNFTRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of NFT contract */
	FString ContractAddress;
	/* An `uint256` token id as string */
	FString TokenId;
	/* The name of chain */
	FString ChainName;
};

class IMMUTABLEOPENAPI_API OpenAPINftsApi::GetNFTResponse : public Response
{
public:
    virtual ~GetNFTResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIGetNFTResult Content;
};

/* List all NFTs
 *
 * List all NFTs on a chain
*/
class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListAllNFTsRequest : public Request
{
public:
    virtual ~ListAllNFTsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListAllNFTsResponse : public Response
{
public:
    virtual ~ListAllNFTsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListNFTsResult Content;
};

/* List mint requests
 *
 * Retrieve the status of all mints for a given contract address
*/
class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListMintRequestsRequest : public Request
{
public:
    virtual ~ListMintRequestsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
	/* The status of the mint request */
	TOptional<OpenAPIMintRequestStatus> Status;
};

class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListMintRequestsResponse : public Response
{
public:
    virtual ~ListMintRequestsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListMintRequestsResult Content;
};

/* List NFTs by contract address
 *
 * List NFTs by contract address
*/
class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListNFTsRequest : public Request
{
public:
    virtual ~ListNFTsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Contract address */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
	/* List of token IDs to filter by */
	TOptional<TArray<FString>> TokenId;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListNFTsResponse : public Response
{
public:
    virtual ~ListNFTsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListNFTsResult Content;
};

/* List NFTs by account address
 *
 * List NFTs by account address
*/
class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListNFTsByAccountAddressRequest : public Request
{
public:
    virtual ~ListNFTsByAccountAddressRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Account address */
	FString AccountAddress;
	/* The name of chain */
	FString ChainName;
	/* The address of contract */
	TOptional<FString> ContractAddress;
	/* List of token IDs to filter by */
	TOptional<TArray<FString>> TokenId;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPINftsApi::ListNFTsByAccountAddressResponse : public Response
{
public:
    virtual ~ListNFTsByAccountAddressResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListNFTsByOwnerResult Content;
};

}
