/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIActivityNFT.h"
#include "OpenAPISalePayment.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPINFTSale
 *
 * The NFT Sale activity details
 */
class IMMUTABLEOPENAPI_API OpenAPINFTSale : public Model
{
public:
    virtual ~OpenAPINFTSale() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The id of order */
	FString OrderId;
	/* The account address of buyer */
	FString To;
	/* The account address of seller */
	FString From;
	TArray<OpenAPIActivityNFT> Asset;
	OpenAPISalePayment Payment;
};

}
