/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIGetMintRequestResult.h"
#include "OpenAPIPage.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIListMintRequestsResult
 *
 * List mint requests
 */
class IMMUTABLEOPENAPI_API OpenAPIListMintRequestsResult : public Model
{
public:
    virtual ~OpenAPIListMintRequestsResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of mint requests */
	TArray<OpenAPIGetMintRequestResult> Result;
	OpenAPIPage Page;
};

}
