/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPINFTBundle.h"
#include "OpenAPIPage.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPISearchNFTsResult
 *
 * Search NFTs result
 */
class IMMUTABLEOPENAPI_API OpenAPISearchNFTsResult : public Model
{
public:
    virtual ~OpenAPISearchNFTsResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of nft bundles */
	TArray<OpenAPINFTBundle> Result;
	OpenAPIPage Page;
};

}
