/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPage.h"
#include "OpenAPIStackQuoteResult.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIQuotesForStacksResult
 *
 * Quotes for stacks result
 */
class IMMUTABLEOPENAPI_API OpenAPIQuotesForStacksResult : public Model
{
public:
    virtual ~OpenAPIQuotesForStacksResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of quotes */
	TArray<OpenAPIStackQuoteResult> Result;
	OpenAPIPage Page;
};

}
