/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIChain.h"
#include "OpenAPICollectionMetadata.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIRefreshCollectionMetadataResult
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPIRefreshCollectionMetadataResult : public Model
{
public:
    virtual ~OpenAPIRefreshCollectionMetadataResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString ContractAddress;
	OpenAPIChain Chain;
	OpenAPICollectionMetadata CollectionMetadata;
};

}
