/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPISaleFee.h"
#include "OpenAPISalePaymentToken.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPISalePayment
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPISalePayment : public Model
{
public:
    virtual ~OpenAPISalePayment() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPISalePaymentToken Token;
	/* The base price of the sale not including any fees */
	FString PriceExcludingFees;
	/* The total price of the sale. Includes the sum of all fees */
	FString PriceIncludingFees;
	/* The fees associated with this sale */
	TArray<OpenAPISaleFee> Fees;
};

}
