/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPITradeBlockchainMetadata
 *
 * The metadata related to the transaction in which the activity occurred
 */
class IMMUTABLEOPENAPI_API OpenAPITradeBlockchainMetadata : public Model
{
public:
    virtual ~OpenAPITradeBlockchainMetadata() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The transaction hash of the trade */
	FString TransactionHash;
	/* EVM block number (uint64 as string) */
	FString BlockNumber;
	/* Transaction index in a block (uint32 as string) */
	FString TransactionIndex;
	/* The log index of the fulfillment event in a block (uint32 as string) */
	FString LogIndex;
};

}
