/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITokensApi.h"

#include "OpenAPIAPIError400.h"
#include "OpenAPIAPIError404.h"
#include "OpenAPIAPIError500.h"
#include "OpenAPIAssetVerificationStatus.h"
#include "OpenAPIGetTokenResult.h"
#include "OpenAPIListTokensResult.h"

namespace ImmutableOpenAPI
{

/* Get single ERC20 token
 *
 * Get single ERC20 token
*/
class IMMUTABLEOPENAPI_API OpenAPITokensApi::GetERC20TokenRequest : public Request
{
public:
    virtual ~GetERC20TokenRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
};

class IMMUTABLEOPENAPI_API OpenAPITokensApi::GetERC20TokenResponse : public Response
{
public:
    virtual ~GetERC20TokenResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIGetTokenResult Content;
};

/* List ERC20 tokens
 *
 * List ERC20 tokens
*/
class IMMUTABLEOPENAPI_API OpenAPITokensApi::ListERC20TokensRequest : public Request
{
public:
    virtual ~ListERC20TokensRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* List of verification status to filter by */
	TOptional<TArray<OpenAPIAssetVerificationStatus>> VerificationStatus;
	/* [Experimental - Canonical token data may be updated] Filter by canonical or non-canonical tokens. */
	TOptional<bool> IsCanonical;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEOPENAPI_API OpenAPITokensApi::ListERC20TokensResponse : public Response
{
public:
    virtual ~ListERC20TokensResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIListTokensResult Content;
};

}
