/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIRefreshMetadataByTokenID.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIRefreshNFTMetadataByTokenIDRequest
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPIRefreshNFTMetadataByTokenIDRequest : public Model
{
public:
    virtual ~OpenAPIRefreshNFTMetadataByTokenIDRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of nft metadata to be refreshed. Total size of the list should not exceed 228 KiB */
	TArray<OpenAPIRefreshMetadataByTokenID> NftMetadata;
};

}
