/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPassportProfileApi.h"

#include "OpenAPIAPIError400.h"
#include "OpenAPIAPIError401.h"
#include "OpenAPIAPIError403.h"
#include "OpenAPIAPIError500.h"
#include "OpenAPIBasicAPIError.h"
#include "OpenAPILinkWalletV2Request.h"
#include "OpenAPIUserInfo.h"
#include "OpenAPIWallet.h"

namespace ImmutableOpenAPI
{

/* Get all info for a Passport user
 *
 * Get all the info for an authenticated Passport user
*/
class IMMUTABLEOPENAPI_API OpenAPIPassportProfileApi::GetUserInfoRequest : public Request
{
public:
    virtual ~GetUserInfoRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class IMMUTABLEOPENAPI_API OpenAPIPassportProfileApi::GetUserInfoResponse : public Response
{
public:
    virtual ~GetUserInfoResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIUserInfo Content;
};

/* Link wallet v2
 *
 * Link an external EOA wallet to an Immutable Passport account by providing an EIP-712 signature.
*/
class IMMUTABLEOPENAPI_API OpenAPIPassportProfileApi::LinkWalletV2Request : public Request
{
public:
    virtual ~LinkWalletV2Request() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<OpenAPILinkWalletV2Request> OpenAPILinkWalletV2Request;
};

class IMMUTABLEOPENAPI_API OpenAPIPassportProfileApi::LinkWalletV2Response : public Response
{
public:
    virtual ~LinkWalletV2Response() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIWallet Content;
};

}
