/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITokenContractType.h"

namespace ImmutableOpenAPI
{

/*
 * OpenAPIActivityToken
 *
 * 
 */
class IMMUTABLEOPENAPI_API OpenAPIActivityToken : public Model
{
public:
    virtual ~OpenAPIActivityToken() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPITokenContractType ContractType;
	/* The contract address */
	FString ContractAddress;
};

}
