/**
 * Indexer Search API
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIModule.h"

IMPLEMENT_MODULE(OpenAPIModule, OpenAPI);
DEFINE_LOG_CATEGORY(LogOpenAPI);

void OpenAPIModule::StartupModule()
{
}

void OpenAPIModule::ShutdownModule()
{
}
