/**
 * Indexer Search API
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * OpenAPI spec version: 1.0
 * Contact: helpmebuild@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIChain.h"
#include "OpenAPIMarket.h"

namespace OpenAPI
{

/*
 * OpenAPIStackQuoteResult
 *
 * Stack quote result
 */
class OPENAPI_API OpenAPIStackQuoteResult : public Model
{
public:
    virtual ~OpenAPIStackQuoteResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPIChain Chain;
	FGuid StackId;
	OpenAPIMarket MarketStack;
	OpenAPIMarket MarketCollection;
};

}
