/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ImmutableOpenAPIModule.h"

IMPLEMENT_MODULE(ImmutableOpenAPIModule, ImmutableOpenAPI);
DEFINE_LOG_CATEGORY(LogImmutableOpenAPI);

void ImmutableOpenAPIModule::StartupModule()
{
}

void ImmutableOpenAPIModule::ShutdownModule()
{
}
