/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIMarketPriceNativeToken.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPIMarketPriceNativeToken::TypeEnum& Value)
{
	switch (Value)
	{
	case OpenAPIMarketPriceNativeToken::TypeEnum::Native:
		return TEXT("NATIVE");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPIMarketPriceNativeToken::TypeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIMarketPriceNativeToken::EnumToString(const OpenAPIMarketPriceNativeToken::TypeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIMarketPriceNativeToken::TypeEnum& Value)
{
	static TMap<FString, OpenAPIMarketPriceNativeToken::TypeEnum> StringToEnum = { 
		{ TEXT("NATIVE"), OpenAPIMarketPriceNativeToken::TypeEnum::Native }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIMarketPriceNativeToken::EnumFromString(const FString& EnumAsString, OpenAPIMarketPriceNativeToken::TypeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIMarketPriceNativeToken::TypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIMarketPriceNativeToken::TypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIMarketPriceNativeToken::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type);
	if (Symbol.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("symbol")); WriteJsonValue(Writer, Symbol.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIMarketPriceNativeToken::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("symbol"), Symbol);

	return ParseSuccess;
}

}
