/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIMintRequestStatus.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPIMintRequestStatus::Values& Value)
{
	switch (Value)
	{
	case OpenAPIMintRequestStatus::Values::Pending:
		return TEXT("pending");
	case OpenAPIMintRequestStatus::Values::Succeeded:
		return TEXT("succeeded");
	case OpenAPIMintRequestStatus::Values::Failed:
		return TEXT("failed");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPIMintRequestStatus::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIMintRequestStatus::EnumToString(const OpenAPIMintRequestStatus::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIMintRequestStatus::Values& Value)
{
	static TMap<FString, OpenAPIMintRequestStatus::Values> StringToEnum = { 
		{ TEXT("pending"), OpenAPIMintRequestStatus::Values::Pending },
		{ TEXT("succeeded"), OpenAPIMintRequestStatus::Values::Succeeded },
		{ TEXT("failed"), OpenAPIMintRequestStatus::Values::Failed }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIMintRequestStatus::EnumFromString(const FString& EnumAsString, OpenAPIMintRequestStatus::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIMintRequestStatus::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIMintRequestStatus::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIMintRequestStatus::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPIMintRequestStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
