/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPISaleFee.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPISaleFee::TypeEnum& Value)
{
	switch (Value)
	{
	case OpenAPISaleFee::TypeEnum::Royalty:
		return TEXT("ROYALTY");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPISaleFee::TypeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPISaleFee::EnumToString(const OpenAPISaleFee::TypeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPISaleFee::TypeEnum& Value)
{
	static TMap<FString, OpenAPISaleFee::TypeEnum> StringToEnum = { 
		{ TEXT("ROYALTY"), OpenAPISaleFee::TypeEnum::Royalty }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPISaleFee::EnumFromString(const FString& EnumAsString, OpenAPISaleFee::TypeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPISaleFee::TypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPISaleFee::TypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPISaleFee::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Amount.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("amount")); WriteJsonValue(Writer, Amount.GetValue());
	}
	if (Type.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type.GetValue());
	}
	if (Recipient.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("recipient")); WriteJsonValue(Writer, Recipient.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPISaleFee::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("amount"), Amount);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("recipient"), Recipient);

	return ParseSuccess;
}

}
