/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICancelOrdersRequestBody.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

void OpenAPICancelOrdersRequestBody::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("account_address")); WriteJsonValue(Writer, AccountAddress);
	Writer->WriteIdentifierPrefix(TEXT("orders")); WriteJsonValue(Writer, Orders);
	Writer->WriteIdentifierPrefix(TEXT("signature")); WriteJsonValue(Writer, Signature);
	Writer->WriteObjectEnd();
}

bool OpenAPICancelOrdersRequestBody::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("account_address"), AccountAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("orders"), Orders);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("signature"), Signature);

	return ParseSuccess;
}

}
