/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICollectionContractType.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPICollectionContractType::Values& Value)
{
	switch (Value)
	{
	case OpenAPICollectionContractType::Values::ERC721:
		return TEXT("ERC721");
	case OpenAPICollectionContractType::Values::ERC1155:
		return TEXT("ERC1155");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPICollectionContractType::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPICollectionContractType::EnumToString(const OpenAPICollectionContractType::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPICollectionContractType::Values& Value)
{
	static TMap<FString, OpenAPICollectionContractType::Values> StringToEnum = { 
		{ TEXT("ERC721"), OpenAPICollectionContractType::Values::ERC721 },
		{ TEXT("ERC1155"), OpenAPICollectionContractType::Values::ERC1155 }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPICollectionContractType::EnumFromString(const FString& EnumAsString, OpenAPICollectionContractType::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPICollectionContractType::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPICollectionContractType::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPICollectionContractType::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPICollectionContractType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
