/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIOrderStatusName.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPIOrderStatusName::Values& Value)
{
	switch (Value)
	{
	case OpenAPIOrderStatusName::Values::Pending:
		return TEXT("PENDING");
	case OpenAPIOrderStatusName::Values::Active:
		return TEXT("ACTIVE");
	case OpenAPIOrderStatusName::Values::Inactive:
		return TEXT("INACTIVE");
	case OpenAPIOrderStatusName::Values::Filled:
		return TEXT("FILLED");
	case OpenAPIOrderStatusName::Values::Expired:
		return TEXT("EXPIRED");
	case OpenAPIOrderStatusName::Values::Cancelled:
		return TEXT("CANCELLED");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPIOrderStatusName::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIOrderStatusName::EnumToString(const OpenAPIOrderStatusName::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIOrderStatusName::Values& Value)
{
	static TMap<FString, OpenAPIOrderStatusName::Values> StringToEnum = { 
		{ TEXT("PENDING"), OpenAPIOrderStatusName::Values::Pending },
		{ TEXT("ACTIVE"), OpenAPIOrderStatusName::Values::Active },
		{ TEXT("INACTIVE"), OpenAPIOrderStatusName::Values::Inactive },
		{ TEXT("FILLED"), OpenAPIOrderStatusName::Values::Filled },
		{ TEXT("EXPIRED"), OpenAPIOrderStatusName::Values::Expired },
		{ TEXT("CANCELLED"), OpenAPIOrderStatusName::Values::Cancelled }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIOrderStatusName::EnumFromString(const FString& EnumAsString, OpenAPIOrderStatusName::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIOrderStatusName::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIOrderStatusName::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIOrderStatusName::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPIOrderStatusName::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
