/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIActivityType.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPIActivityType::Values& Value)
{
	switch (Value)
	{
	case OpenAPIActivityType::Values::Mint:
		return TEXT("mint");
	case OpenAPIActivityType::Values::Burn:
		return TEXT("burn");
	case OpenAPIActivityType::Values::Transfer:
		return TEXT("transfer");
	case OpenAPIActivityType::Values::Sale:
		return TEXT("sale");
	case OpenAPIActivityType::Values::Deposit:
		return TEXT("deposit");
	case OpenAPIActivityType::Values::Withdrawal:
		return TEXT("withdrawal");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPIActivityType::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIActivityType::EnumToString(const OpenAPIActivityType::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIActivityType::Values& Value)
{
	static TMap<FString, OpenAPIActivityType::Values> StringToEnum = { 
		{ TEXT("mint"), OpenAPIActivityType::Values::Mint },
		{ TEXT("burn"), OpenAPIActivityType::Values::Burn },
		{ TEXT("transfer"), OpenAPIActivityType::Values::Transfer },
		{ TEXT("sale"), OpenAPIActivityType::Values::Sale },
		{ TEXT("deposit"), OpenAPIActivityType::Values::Deposit },
		{ TEXT("withdrawal"), OpenAPIActivityType::Values::Withdrawal }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIActivityType::EnumFromString(const FString& EnumAsString, OpenAPIActivityType::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIActivityType::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIActivityType::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIActivityType::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPIActivityType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
