/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIItem.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPIItem::TypeEnum& Value)
{
	switch (Value)
	{
	case OpenAPIItem::TypeEnum::Native:
		return TEXT("NATIVE");
	case OpenAPIItem::TypeEnum::ERC20:
		return TEXT("ERC20");
	case OpenAPIItem::TypeEnum::ERC721:
		return TEXT("ERC721");
	case OpenAPIItem::TypeEnum::ERC1155:
		return TEXT("ERC1155");
	case OpenAPIItem::TypeEnum::ERC721COLLECTION:
		return TEXT("ERC721_COLLECTION");
	case OpenAPIItem::TypeEnum::ERC1155COLLECTION:
		return TEXT("ERC1155_COLLECTION");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPIItem::TypeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIItem::EnumToString(const OpenAPIItem::TypeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIItem::TypeEnum& Value)
{
	static TMap<FString, OpenAPIItem::TypeEnum> StringToEnum = { 
		{ TEXT("NATIVE"), OpenAPIItem::TypeEnum::Native },
		{ TEXT("ERC20"), OpenAPIItem::TypeEnum::ERC20 },
		{ TEXT("ERC721"), OpenAPIItem::TypeEnum::ERC721 },
		{ TEXT("ERC1155"), OpenAPIItem::TypeEnum::ERC1155 },
		{ TEXT("ERC721_COLLECTION"), OpenAPIItem::TypeEnum::ERC721COLLECTION },
		{ TEXT("ERC1155_COLLECTION"), OpenAPIItem::TypeEnum::ERC1155COLLECTION }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIItem::EnumFromString(const FString& EnumAsString, OpenAPIItem::TypeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIItem::TypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIItem::TypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIItem::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type);
	Writer->WriteIdentifierPrefix(TEXT("amount")); WriteJsonValue(Writer, Amount);
	Writer->WriteIdentifierPrefix(TEXT("contract_address")); WriteJsonValue(Writer, ContractAddress);
	Writer->WriteIdentifierPrefix(TEXT("token_id")); WriteJsonValue(Writer, TokenId);
	Writer->WriteObjectEnd();
}

bool OpenAPIItem::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("amount"), Amount);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("contract_address"), ContractAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("token_id"), TokenId);

	return ParseSuccess;
}

}
