/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIOrganisationTier.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPIOrganisationTier::Values& Value)
{
	switch (Value)
	{
	case OpenAPIOrganisationTier::Values::Common:
		return TEXT("common");
	case OpenAPIOrganisationTier::Values::Uncommon:
		return TEXT("uncommon");
	case OpenAPIOrganisationTier::Values::Rare:
		return TEXT("rare");
	case OpenAPIOrganisationTier::Values::Epic:
		return TEXT("epic");
	case OpenAPIOrganisationTier::Values::Legendary:
		return TEXT("legendary");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPIOrganisationTier::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIOrganisationTier::EnumToString(const OpenAPIOrganisationTier::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIOrganisationTier::Values& Value)
{
	static TMap<FString, OpenAPIOrganisationTier::Values> StringToEnum = { 
		{ TEXT("common"), OpenAPIOrganisationTier::Values::Common },
		{ TEXT("uncommon"), OpenAPIOrganisationTier::Values::Uncommon },
		{ TEXT("rare"), OpenAPIOrganisationTier::Values::Rare },
		{ TEXT("epic"), OpenAPIOrganisationTier::Values::Epic },
		{ TEXT("legendary"), OpenAPIOrganisationTier::Values::Legendary }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIOrganisationTier::EnumFromString(const FString& EnumAsString, OpenAPIOrganisationTier::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIOrganisationTier::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIOrganisationTier::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIOrganisationTier::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPIOrganisationTier::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
