/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVerificationRequestStatus.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

inline FString ToString(const OpenAPIVerificationRequestStatus::Values& Value)
{
	switch (Value)
	{
	case OpenAPIVerificationRequestStatus::Values::Completed:
		return TEXT("completed");
	case OpenAPIVerificationRequestStatus::Values::Pending:
		return TEXT("pending");
	}

	UE_LOG(LogImmutableOpenAPI, Error, TEXT("Invalid OpenAPIVerificationRequestStatus::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIVerificationRequestStatus::EnumToString(const OpenAPIVerificationRequestStatus::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIVerificationRequestStatus::Values& Value)
{
	static TMap<FString, OpenAPIVerificationRequestStatus::Values> StringToEnum = { 
		{ TEXT("completed"), OpenAPIVerificationRequestStatus::Values::Completed },
		{ TEXT("pending"), OpenAPIVerificationRequestStatus::Values::Pending }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIVerificationRequestStatus::EnumFromString(const FString& EnumAsString, OpenAPIVerificationRequestStatus::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIVerificationRequestStatus::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIVerificationRequestStatus::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIVerificationRequestStatus::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPIVerificationRequestStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
