/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPINFTMetadataAttributeValue.h"

#include "ImmutableOpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOpenAPI
{

void OpenAPINFTMetadataAttributeValue::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteValue(Value);
}

bool OpenAPINFTMetadataAttributeValue::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	if (!JsonValue->TryGetString(Value))
		return false;

	return true;
}

}
