name: Release with Submodules

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: ./.github/actions/checkout  # Reference the local copy
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Create release archive with submodules
        run: zip -r release-with-submodules.zip .

      - name: Upload release asset
        uses: ./.github/actions/upload-release-asset  # Reference the local copy
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-with-submodules.zip
          asset_name: release-with-submodules.zip
          asset_content_type: application/zip
