---
name: 'Create Release'

on:
  workflow_run:
    workflows: ["Tag Release"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: true
          
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configurationJson: |
            {
              "pr_template": "- #{{TITLE}} (##{{NUMBER}})",
              "categories": [
                {
                    "title": "## Features",
                    "labels": ["feature", "feat"]
                },
                {
                    "title": "## Fixes",
                    "labels": ["fix"]
                }
              ]
            }
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
            body: |
              ${{steps.github_release.outputs.changelog}}
