name: Release with Submodules

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Ensures all submodules are included
          fetch-depth: 0         # Fetches full history for correct release packaging

      - name: Create release archive with submodules
        run: zip -r release-with-submodules.zip .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-with-submodules.zip
          asset_name: release-with-submodules.zip
          asset_content_type: application/zip
